insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("notebook", "computer", 150, "삼성전자", 50, "최신형")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("desktop", "computer", 150, "LG전자", 20, "구형")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("ball", "ball", 5, "아디다스", 15, "튼튼함")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("운동화", "shoes", 10, "아디다스", 30, "가볍고 튼튼해요")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("TV", "tv", 200, "LG전자", 30, "최신형 TV")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("OLEDTV", "tv", 200, "삼성전자", 30, "최신형 선명한 TV")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("IPHONE", "cellphone", 150, "애플", 20, "최신형 아이폰")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("GALAXYS10", "cellphone", 150, "삼성전자", 150, "최신형 휴대폰")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("GALAXYS5", "cellphone", 10, "삼성전자", 20, "구형 휴대폰")
insert into product_table(name, category, price, manufacturer, unit_In_Stock, description) values ("런닝화", "shoes", 15, "프로스펙스", 70, "편한 운동화")